/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.enbd;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AccountSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4300198959848744531L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AccountSchema\",\"namespace\":\"com.enbd\",\"fields\":[{\"name\":\"AccountId\",\"type\":\"long\"},{\"name\":\"AccountType\",\"type\":\"int\",\"valid_values\":\"1,2,3,4\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AccountSchema> ENCODER =
      new BinaryMessageEncoder<AccountSchema>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AccountSchema> DECODER =
      new BinaryMessageDecoder<AccountSchema>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AccountSchema> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AccountSchema> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AccountSchema>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AccountSchema to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AccountSchema from a ByteBuffer. */
  public static AccountSchema fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long AccountId;
  @Deprecated public int AccountType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AccountSchema() {}

  /**
   * All-args constructor.
   * @param AccountId The new value for AccountId
   * @param AccountType The new value for AccountType
   */
  public AccountSchema(java.lang.Long AccountId, java.lang.Integer AccountType) {
    this.AccountId = AccountId;
    this.AccountType = AccountType;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return AccountId;
    case 1: return AccountType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: AccountId = (java.lang.Long)value$; break;
    case 1: AccountType = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'AccountId' field.
   * @return The value of the 'AccountId' field.
   */
  public java.lang.Long getAccountId() {
    return AccountId;
  }

  /**
   * Sets the value of the 'AccountId' field.
   * @param value the value to set.
   */
  public void setAccountId(java.lang.Long value) {
    this.AccountId = value;
  }

  /**
   * Gets the value of the 'AccountType' field.
   * @return The value of the 'AccountType' field.
   */
  public java.lang.Integer getAccountType() {
    return AccountType;
  }

  /**
   * Sets the value of the 'AccountType' field.
   * @param value the value to set.
   */
  public void setAccountType(java.lang.Integer value) {
    this.AccountType = value;
  }

  /**
   * Creates a new AccountSchema RecordBuilder.
   * @return A new AccountSchema RecordBuilder
   */
  public static com.enbd.AccountSchema.Builder newBuilder() {
    return new com.enbd.AccountSchema.Builder();
  }

  /**
   * Creates a new AccountSchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AccountSchema RecordBuilder
   */
  public static com.enbd.AccountSchema.Builder newBuilder(com.enbd.AccountSchema.Builder other) {
    return new com.enbd.AccountSchema.Builder(other);
  }

  /**
   * Creates a new AccountSchema RecordBuilder by copying an existing AccountSchema instance.
   * @param other The existing instance to copy.
   * @return A new AccountSchema RecordBuilder
   */
  public static com.enbd.AccountSchema.Builder newBuilder(com.enbd.AccountSchema other) {
    return new com.enbd.AccountSchema.Builder(other);
  }

  /**
   * RecordBuilder for AccountSchema instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AccountSchema>
    implements org.apache.avro.data.RecordBuilder<AccountSchema> {

    private long AccountId;
    private int AccountType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.enbd.AccountSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.AccountId)) {
        this.AccountId = data().deepCopy(fields()[0].schema(), other.AccountId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.AccountType)) {
        this.AccountType = data().deepCopy(fields()[1].schema(), other.AccountType);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AccountSchema instance
     * @param other The existing instance to copy.
     */
    private Builder(com.enbd.AccountSchema other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.AccountId)) {
        this.AccountId = data().deepCopy(fields()[0].schema(), other.AccountId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.AccountType)) {
        this.AccountType = data().deepCopy(fields()[1].schema(), other.AccountType);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'AccountId' field.
      * @return The value.
      */
    public java.lang.Long getAccountId() {
      return AccountId;
    }

    /**
      * Sets the value of the 'AccountId' field.
      * @param value The value of 'AccountId'.
      * @return This builder.
      */
    public com.enbd.AccountSchema.Builder setAccountId(long value) {
      validate(fields()[0], value);
      this.AccountId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'AccountId' field has been set.
      * @return True if the 'AccountId' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'AccountId' field.
      * @return This builder.
      */
    public com.enbd.AccountSchema.Builder clearAccountId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'AccountType' field.
      * @return The value.
      */
    public java.lang.Integer getAccountType() {
      return AccountType;
    }

    /**
      * Sets the value of the 'AccountType' field.
      * @param value The value of 'AccountType'.
      * @return This builder.
      */
    public com.enbd.AccountSchema.Builder setAccountType(int value) {
      validate(fields()[1], value);
      this.AccountType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'AccountType' field has been set.
      * @return True if the 'AccountType' field has been set, false otherwise.
      */
    public boolean hasAccountType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'AccountType' field.
      * @return This builder.
      */
    public com.enbd.AccountSchema.Builder clearAccountType() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AccountSchema build() {
      try {
        AccountSchema record = new AccountSchema();
        record.AccountId = fieldSetFlags()[0] ? this.AccountId : (java.lang.Long) defaultValue(fields()[0]);
        record.AccountType = fieldSetFlags()[1] ? this.AccountType : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AccountSchema>
    WRITER$ = (org.apache.avro.io.DatumWriter<AccountSchema>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AccountSchema>
    READER$ = (org.apache.avro.io.DatumReader<AccountSchema>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
